---
driver:
  name: vagrant
provisioner:
  name: puppet_apply
  manifests_path: test/fixtures/manifests
  require_chef_for_busser: false
  require_puppet_omnibus: true
verifier:
  name: inspec
  suite_name: hardening
platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: ubuntu-20.04
  - name: debian-9.6
  - name: debian-10.2
  - name: centos-7.7
  - name: centos-8.1
suites:
  - name: puppet6
