---
driver:
  name: vagrant
provisioner:
  name: puppet_apply
  manifests_path: test/fixtures/manifests
  require_chef_for_busser: false
  require_puppet_omnibus: true
verifier:
  name: inspec
  suite_name: default
platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: debian-8.11
  - name: debian-9.6
  - name: centos-6.10
  - name: centos-7.7
suites:
  - name: puppet5

