---
driver:
  name: vagrant
provisioner:
  name: puppet_apply
  require_chef_for_busser: false
  manifest: init.pp
  manifests_path: examples
verifier:
  name: inspec
  suite_name: default
  inspec_tests:
    - https://github.com/dev-sec/tests-ssh-hardening
platforms:
- name: ubuntu-14.04
  provisioner:
    puppet_apt_repo: https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
    puppet_apt_collections_repo: https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
- name: ubuntu-16.04
  provisioner:
    puppet_apt_collections_repo: https://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
- name: debian-7.11
  provisioner:
    puppet_apt_repo: https://apt.puppetlabs.com/puppetlabs-release-wheezy.deb
    puppet_apt_collections_repo: https://apt.puppetlabs.com/puppetlabs-release-pc1-wheezy.deb
- name: debian-8.6
  provisioner:
    puppet_apt_repo: https://apt.puppetlabs.com/puppetlabs-release-jessie.deb
    puppet_apt_collections_repo: https://apt.puppetlabs.com/puppetlabs-release-pc1-jessie.deb
- name: centos-6.8
  provisioner:
    puppet_yum_repo: https://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm
    puppet_yum_collections_repo: http://yum.puppetlabs.com/puppetlabs-release-pc1-el-6.noarch.rpm
- name: centos-7.2
  provisioner:
    puppet_yum_repo: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
    puppet_yum_collections_repo: http://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
suites:
  - name: puppet3
    excludes: [
     'ubuntu-16.04'
    ]
  - name: puppet4
    provisioner:
      puppet_omnibus_url: https://raw.githubusercontent.com/petems/puppet-install-shell/master/install_puppet_agent.sh
      require_puppet_collections: true

