language: ruby
install: sudo ln -s $TRAVIS_BUILD_DIR `dirname $TRAVIS_BUILD_DIR`/ssh
script:
  - "bundle install && bundle exec rake lint spec SPEC_OPTS='--format documentation' "
  - "puppet apply --modulepath=`dirname $TRAVIS_BUILD_DIR` --noop tests/client.pp"
  - "puppet apply --modulepath=`dirname $TRAVIS_BUILD_DIR` --noop tests/server.pp"
rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
branches:
  only:
   - master
env:
  - PUPPET_GEM_VERSION="~> 2.6"
  - PUPPET_GEM_VERSION="~> 2.7"
  - PUPPET_GEM_VERSION="~> 3.0"
  - PUPPET_GEM_VERSION="~> 3.1"
  - PUPPET_GEM_VERSION="~> 3.2"
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.7"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 2.6"
    - rvm: ruby-head
      env: PUPPET_GEM_VERSION="~> 2.6"
