name 'attachmentgenie-ssh'
version '1.3.2'

author 'Eivind Uggedal <eivind@uggedal.com>'
license 'MIT License'
project_page 'https://github.com/attachmentgenie/puppet-module-ssh'
source 'git://github.com/attachmentgenie/puppet-module-ssh.git'
summary 'Puppet ssh Module'
description 'Module for configuring ssh.'
dependency 'puppetlabs/stdlib', '>=2.2.1'
